apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: cloudflare-client-replacement-transformer
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: krmfnbuiltin
replacements:
  - source:
      name: autocloud-values
      fieldPath: data.cluster.argocd.domainPrefix
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
          - spec.tls.0.secretName
        options:
          delimiter: "."
          index: 0
  - source:
      name: autocloud-values
      fieldPath: data.cloudflare.dnsZone
    targets:
      - select:
          kind: Ingress
          name: argocd-cloudflare
        fieldPaths:
          - spec.rules.0.host.!!regex.^\w+\\.(\.*)$.1
          - spec.tls.0.hosts.0.!!regex.^\w+\\.(\.*)$.1
          - spec.tls.0.secretName.!!regex.^\w+\\.(\.*)-tls$.1
  - source:
      name: autocloud-values
      fieldPath: data.cloudflare.tunnel_id
    targets:
      - select:
          kind: Ingress
          name: argocd-cloudflare
        fieldPaths:
          - metadata.annotations.external-dns\.alpha\.kubernetes\.io/target
        options:
          delimiter: "."
          index: 0
  - source:
      name: autocloud-values
      fieldPath: data.ovh.dnsZone
    targets:
      - select:
          kind: Ingress
          name: argocd-sish
        fieldPaths:
          - spec.rules.0.host.!!regex.^\w+\\.(\.*)$.1
          - spec.tls.0.hosts.0.!!regex.^\w+\\.(\.*)$.1
          - spec.tls.0.secretName.!!regex.^\w+\\.(\.*)-tls$.1
          - metadata.annotations.external-dns\.alpha\.kubernetes\.io/target
