apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: external-dns-replacement-transformer
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: krmfnbuiltin
source: values.yaml
replacements:
  - source:
      name: autocloud-values
      fieldPath: data.cluster.id
    targets:
      - select:
          kind: ConfigMap
          name: external-dns
        fieldPaths:
          - data.EXTERNAL_DNS_ID
