apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

# Import decoded platform secrets
generators:
  - ../../secrets

# Replace secrets in configuration
replacements:
  - source:
      name: autocloud-secrets
      fieldPath: data.cloudflare.credentials\.json
    targets:
      - select:
          kind: Secret
          name: cloudflared
        fieldPaths:
          - stringData.credentials\.json

# Remove secrets
transformers:
  - ../../secrets/remove
