apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: edge
  app.kubernetes.io/part-of: autocloud

resources:
  - deployment.yaml

patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cloudflared
      annotations:
        internal.config.kubernetes.io/needsHashSuffix: enabled
  - |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: cloudflared
      annotations:
        internal.config.kubernetes.io/needsHashSuffix: enabled

transformers:
  - cloudflare-client-secrets-replacements.yaml
