apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: edge
  app.kubernetes.io/part-of: autocloud

resources:
  - deployment.yaml

transformers:
  - cloudflare-client-secrets-replacements.yaml
