apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sish-tunnel.fullname" . }}
  labels:
    {{- include "sish-tunnel.labels" . | nindent 4 }}
data:
    id_rsa: {{ .Values.sish.local_ssh_key | b64enc }}
