apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  # This one points to the kustomization installed by iknite
  - argocd-ingress.yaml
  - secrets.yaml

transformers:
  - sops-transformer.yaml

