apiVersion: iknite.krm.kaweezle.com/v1beta1
kind: SopsTranformer
metadata:
  name: secrets
  annotations:
    # https://kubectl.docs.kubernetes.io/guides/extending_kustomize/#required-alpha-flags
    config.kubernetes.io/function: |
      exec:
        path: krmfnsops
spec:
  files: []
