creation_rules:
  - encrypted_regex: "^(data|stringData|.*_keys?|admin|adminKey|password)$"
    # Your AGE public key (obtain it with cat ~/.config/sops/age/keys.txt| age-keygen -y)
    age: age1fs48f8rw9gj49ss5fapsy8euqln0dtrc5yg35fuq7c930jtkveps2swvt6
