apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: citest
spec:
  generators:
    - list:
        elements:
          - package: cert-manager
            namespace: cert-manager
          - package: sish-client
            namespace: traefik
          - package: cloudflare-client
            namespace: traefik
          - package: external-dns-ovh
            namespace: argocd
  template:
    metadata:
      name: "{{ package }}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: "{{ namespace }}"
        server: https://kubernetes.default.svc
      project: default
      source:
        path: "packages/{{ package }}"
        repoURL: https://github.com/antoinemartin/autocloud.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
