apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chisel-client
  namespace: argocd
  annotations:
    autocloud/local-application: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: packages/chisel-client
    repoURL: https://github.com/antoinemartin/autocloud.git
    targetRevision: deploy/citest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
