apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./sish-client.yaml
  - ./argocd-ingress.yaml
  - ./argocd-ingress-cloudflare.yaml

generators:
  - ./sops-generator.yaml
