apiVersion: v1
kind: Secret
metadata:
  name: sish-ssh-credentials
  labels:
    app.kubernetes.io/name: sish-ssh-credentials
    app.kubernetes.io/component: edge
    app.kubernetes.io/part-of: autocloud
stringData:
  id_ed25519: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACA4nXPm/isSCn3Jmsj2cqBIRhoZ6ZTegcxgFZhDKJXDTwAAAJgOYygIDmMo
    CAAAAAtzc2gtZWQyNTUxOQAAACA4nXPm/isSCn3Jmsj2cqBIRhoZ6ZTegcxgFZhDKJXDTw
    AAAECApDmEpcj6BVxPhdt2ZJB5llYEcGKmapyGXlg/y9Sjejidc+b+KxIKfcmayPZyoEhG
    GhnplN6BzGAVmEMolcNPAAAAD2FudG9pbmVAbXJ0bi5mcgECAwQFBg==
    -----END OPENSSH PRIVATE KEY-----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sish-client
  labels:
    app.kubernetes.io/name: "sish-client"
    app.kubernetes.io/component: edge
    app.kubernetes.io/part-of: autocloud
data:
  config: |
    PubkeyAcceptedKeyTypes +ssh-rsa
    Host sishserver
      HostName mydomain.link
      Port 2222
      BatchMode yes
      IdentityFile ~/.ssh_keys/id_ed25519
      IdentitiesOnly yes
      LogLevel ERROR
      ServerAliveInterval 10
      ServerAliveCountMax 2
      RemoteCommand sni-proxy=true
      RemoteForward argocd.mydomain.link:443 traefik.traefik.svc:443
  known_hosts: |
    [mydomain.link]:2222 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEAfLUpTj0fn5sJFW6agmLMsvEacMBvXocyzHLW+AOSQ
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sish-client
  labels:
    app.kubernetes.io/name: "sish-client"
    app.kubernetes.io/component: edge
    app.kubernetes.io/part-of: autocloud
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: "sish-client"
      app.kubernetes.io/component: edge
      app.kubernetes.io/part-of: autocloud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "sish-client"
        app.kubernetes.io/component: edge
        app.kubernetes.io/part-of: autocloud
    spec:
      volumes:
        - name: ssh-config
          configMap:
            name: sish-client
            defaultMode: 0600
        - name: ssh-keys
          secret:
            secretName: sish-ssh-credentials
            defaultMode: 0600
      containers:
        - name: sish-client
          image: kroniak/ssh-client:3.15
          imagePullPolicy: IfNotPresent
          command: [/usr/bin/ssh, sishserver]
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: ssh-config
              mountPath: /root/.ssh
            - name: ssh-keys
              mountPath: /root/.ssh_keys
