---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sish-client
  namespace: traefik
  labels:
    app.kubernetes.io/name: "sish-client"
    app.kubernetes.io/component: edge
    app.kubernetes.io/part-of: autocloud
data:
  config: |
    PubkeyAcceptedKeyTypes +ssh-rsa
    Host sishserver
      HostName holepunch.in
      Port 2222
      BatchMode yes
      IdentityFile ~/.ssh_keys/id_rsa
      IdentitiesOnly yes
      LogLevel ERROR
      ServerAliveInterval 10
      ServerAliveCountMax 2
      RemoteCommand sni-proxy=true
      RemoteForward citest.holepunch.in:443 traefik.traefik.svc:443
  known_hosts: |
    [holepunch.in]:2222 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID+3abW2y3T5dodnI5O1Z/2KlIdH3bwnbGDvCFf13zlh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sish-client
  namespace: traefik
  labels:
    app.kubernetes.io/name: "sish-client"
    app.kubernetes.io/component: edge
    app.kubernetes.io/part-of: autocloud
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: "sish-client"
      app.kubernetes.io/component: edge
      app.kubernetes.io/part-of: autocloud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "sish-client"
        app.kubernetes.io/component: edge
        app.kubernetes.io/part-of: autocloud
    spec:
      volumes:
        - name: ssh-config
          configMap:
            name: sish-client
            defaultMode: 0600
        - name: ssh-keys
          secret:
            secretName: sish-ssh-credentials
            defaultMode: 0600
      containers:
        - name: sish-client
          image: kroniak/ssh-client:3.15
          imagePullPolicy: IfNotPresent
          command: [/usr/bin/ssh, sishserver]
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: ssh-config
              mountPath: /root/.ssh
            - name: ssh-keys
              mountPath: /root/.ssh_keys
