apiVersion: v1
kind: ConfigMap
metadata:
  name: chisel-client
  labels:
    app.kubernetes.io/name: "chisel-client"
data:
  CHISEL_SERVER: https://gitlab.openance.dev/chisel
  CHISEL_TUNNEL: R:30443:traefik.traefik.svc:80
---
apiVersion: v1
kind: Secret
metadata:
  name: chisel-client-auth
  labels:
    app.kubernetes.io/name: chisel-client-auth
stringData:
  AUTH: username:password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chisel-client
  labels:
    app.kubernetes.io/name: "chisel-client"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: "chisel-client"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "chisel-client"
    spec:
      containers:
        - name: chisel-client
          image: jpillora/chisel:1.7.7
          imagePullPolicy: Always
          command:
            - /app/chisel
          args:
            - client
            - "-v"
            - "$(CHISEL_SERVER)"
            - "$(CHISEL_TUNNEL)"
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
            limits:
              cpu: 100m
              memory: 100Mi
          envFrom:
            - configMapRef:
                name: chisel-client
            - secretRef:
                name: chisel-client-auth
