apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./chisel-client.yaml

# Import decoded platform secrets
generators:
  - ../../secrets

# Replace secrets in configuration
replacements:
  - source:
      name: autocloud-secrets
      fieldPath: data.chisel.AUTH
    targets:
      - select:
          kind: Secret
          name: chisel-client-auth
        fieldPaths:
          - stringData.AUTH

# Remove secrets
transformers:
  - ../../secrets/remove
