apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sish.fullname" . }}-server-keys
  labels:
    {{- include "sish.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.sish.server_keys }}
data:
  {{- range $name, $key := .Values.sish.server_keys }}
    {{ $name }}: {{ $key | b64enc }}
  {{- end }}
{{- end }}
