ingress-controller:
    config:
        apisix:
            adminKey: ENC[AES256_GCM,data:jDDkza62YJ6bjdg/0KWVLOVWPhQPdk+RonLxOxKdcqc=,iv:J55y1vLlKilYcQWCEcspU6VE+4FGrkEPuPVAIaTaZx8=,tag:AJaJkJcXctGDuMxsJEWXNQ==,type:str]
admin:
    credentials:
        admin: ENC[AES256_GCM,data:RAJvTEcJ6XVhVHqfVQyYxs39g+TieMnq3o8PkZATlQo=,iv:Ad3HVrE50CqSGGEI0DoC/1dCeMqIqWntwmmJwtOPi3A=,tag:d1JC7Wy7YTEdYyLP6OhbOA==,type:str]
dashboard:
    config:
        authentication:
            users:
                - username: admin
                  password: ENC[AES256_GCM,data:ne6UfipxkOA=,iv:Czncb3XzW22tAeMV9xf7NR+PbwCkDO93jvovEJiwHxs=,tag:K52WAd2EWE1YyrC/fghH+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age166k86d56ejs2ydvaxv2x3vl3wajny6l52dlkncf2k58vztnlecjs0g5jqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRVlXN0lucFpiWGZ0emdC
            UlM4d1Y0d3VUQVU3eXYvekxyRE9uTkVVQ3drCkVKZXVKUTNNL2lISGhiYnZlazdy
            REx4QWMzdnlzd2FjTW15cWhSNHZCSDAKLS0tIENtV2ZqZ3A0U0EreGw3SmJPbEd5
            NkZwNStUcjFnYXR5a1kzUE5hemtDVzAKb9PtRe+hRZicVeQqzTVrnNUT8EYhXo90
            sju2jTg2lAvdlYSfVLfwB6fyi/951frpKQKXwFwqJXHGve1xKyAy7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-01T14:48:19Z"
    mac: ENC[AES256_GCM,data:oK9xWYRjCK8y+670lypJT/4LFTxVC3LHLhOYq0aGx/auPQe8hjG65AaP/e+3XdYbpFx6SNoVrT/Rc3zQW8/ItI3yVTZ+WNu1mawOz0yGLPQudJ3YgiYr2vY27GIqSghuLpfZvX4jBm48wbTzqwdo2OfQqhpXSFf4Fu+a5EvWlHo=,iv:B9koERB4SMNpytn2TLFkzTveH0A5LcwZYPrM4MPXhyk=,tag:ccVKcgEGJGzkcda6NzFgDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*_keys?|admin|adminKey|password)$
    version: 3.7.3
