# The ArgoCD standard installation creates this secret. This is why our
# additions need to go through a strategic merge patch
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argocd-secret
  labels:
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
stringData:
  # the non replaced password is "password"
  admin.password: $2a$10$xdlX460lf/WbJNZU5bBoROj6U7oKgPbEcBrnXaemA6gsCzrAJtQ3y
  admin.passwordMtime: "2022-08-30T11:26:42Z"
  webhook.github.secret: ZxqGggxGD070l3dx
  dex.github.clientSecret: 7lqt6nasit6kjtvptmy2dzy1dr796orn5xh05ru1
