# This secret is a credential template to access private repositories
# see https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repository-credentials
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repo-creds
  name: github-private-repo-creds
type: Opaque
stringData:
  type: git
  url: https://github.com/
  username: username
  password: ghp_eQtZGJqPrUMNPJs8AMebNQk4GbYNMGjD8vNr
---
# This secret is mounted on the argocd-repo-server in order to decrypt secrets
# upon installation.
apiVersion: v1
kind: Secret
metadata:
  name: argocd-sops-private-keys
type: Opaque
data:
  # The non transformed value is the content of sample_age_key.txt
  age_key.txt: IyBjcmVhdGVkOiAyMDIzLTAxLTE5VDE5OjQxOjQ1WgojIHB1YmxpYyBrZXk6IGFnZTE2Nms4NmQ1NmVqczJ5ZHZheHYyeDN2bDN3YWpueTZsNTJkbGtuY2YyazU4dnp0bmxlY2pzMGc1anFxCkFHRS1TRUNSRVQtS0VZLTE1UktUUFFDQ0xXTTdFSFE4SkVQMFRRTFVXSkFFQ1ZQNzMzMk0zWlAwUkw5UjdKVDdNWjZTWTc5VjhRCg==
