# This transformation replaces all the dumb passwords and secrets
# with the actual ones
apiVersion: krmfnbuiltin.kaweezle.com/v1alpha1
kind: ReplacementTransformer
metadata:
  name: argocd-secrets-replacements
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: krmfnbuiltin
source: ../../secrets
replacements:
  - source:
      name: autocloud-secrets
      fieldPath: data.github.password
    targets:
      - select:
          kind: Secret
          name: github-private-repo-creds
        fieldPaths:
          - stringData.password
  - source:
      name: autocloud-secrets
      fieldPath: data.github.ssh_key
    targets:
      - select:
          kind: Secret
          name: github-private-repo-creds-ssh
        fieldPaths:
          - stringData.sshPrivateKey
  - source:
      name: autocloud-secrets
      fieldPath: data.sops.age_key\.txt
      options:
        encoding: base64
    targets:
      - select:
          kind: Secret
          name: argocd-sops-private-keys
        fieldPaths:
          - data.age_key\.txt
  - source:
      name: autocloud-secrets
      fieldPath: data.argocd.admin_password
      options:
        encoding: bcrypt
    targets:
      - select:
          kind: Secret
          name: argocd-secret
        fieldPaths:
          - stringData.admin\.password
  - source:
      name: autocloud-secrets
      fieldPath: data.github.webhook_secret
    targets:
      - select:
          kind: Secret
          name: argocd-secret
        fieldPaths:
          - stringData.webhook\.github\.secret
  - source:
      name: autocloud-secrets
      fieldPath: data.github.oidc_client_secret
    targets:
      - select:
          kind: Secret
          name: argocd-secret
        fieldPaths:
          - stringData.dex\.github\.clientSecret
