apiVersion: v1
kind: Secret
metadata:
    labels:
        argocd.argoproj.io/secret-type: repo-creds
    name: github-private-repo-creds
    namespace: argocd
type: Opaque
stringData:
    type: ENC[AES256_GCM,data:LFI3,iv:puiHOJiumKYIes6CWZI9MuZxDFn9cdKIvq6ehOTaw8o=,tag:oIiwRRzhqu+YyIk2VGAK6A==,type:str]
    url: ENC[AES256_GCM,data:Z9mR1b6TSlr2JbtiYIhqt5cZtg==,iv:NWecLlSo4BuO1W5hOy2TZvXegtGOximYpOBEUpAdgOA=,tag:M+/4G1z/YehweAMsAqS4ZA==,type:str]
    username: ENC[AES256_GCM,data:7MjNFbFvIVM=,iv:snQ7Bh2QONy3zVsjw0LzC22+hYbOiHKshRJyaIuwrhM=,tag:H0W7MvvUBwxNQVkBJ3ZX6Q==,type:str]
    password: ENC[AES256_GCM,data:kFGV3w/QbF1O0sivCN85v8H7EJqt0CU3cvaM5CkmalwTMEKr9DT2Hw==,iv:5e4izYzCyQUMYtrnOKmqNZs5wOaHTOBbwN0fSi4z1f8=,tag:egwstLVx0KP5YdgMVqP0aA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fs48f8rw9gj49ss5fapsy8euqln0dtrc5yg35fuq7c930jtkveps2swvt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cS9HM2lTUmJ3WDkyemcx
            dnZ3MTUxRkkxWjZoZnY1K0xlbzd5UEVscGdnClVuZFIwQzNoKzV0TFN2NkJvdk9Y
            eUxVazJ5aFBkOXFyYTBXTVlnMzREUXMKLS0tIHo5MzRkTGVyY295WmlGOUc0Rmh5
            R0hMZWYzVmcvTUwxTlFsaStyWFNLbGsKa8XXJmR0uAXZxwe4nZOua0zh3d8PFG1T
            Hbo2sTjALBPn2lgTNLFHho7IWmvsrrUnhl4siCT1GPXE1764YEw9gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-17T16:14:30Z"
    mac: ENC[AES256_GCM,data:ImjbwN0g8SmJ6EJ9+G9bSe6mVQAW38ZahIvCVCG8JkHtIMQi0o2OQt18MF30Vot+A34NlZdvDyyVyCHIHoDluZc5I/XH3R51X/D9a5rDCUj+vTx6pdDx4wyzk5gIdubtC0ClW9f+drwzNo/t4JDp9d3/r5lDw2SNSrGFq617wgE=,iv:W6ibTwXHbAQAE9AXSFCKPdJa1iFsbj4ueFdd9jIzVxw=,tag:C2HQt6c+LC94ThUl/lE1Jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: argocd-sops-private-keys
    namespace: argocd
type: Opaque
data:
    age_key.txt: ENC[AES256_GCM,data:/AqW9ao56x3995YA25ZTqRYW4OLAED0FgmLzSqYFSbCKx9xCtXiJ5x6E77vwW2vwD93R8Esz8ZtJiDJ0BkpleaEivUewKydP366KoN5oA5/pV6C5RgAsAG7nC48KHtJ80q+4IuQH26ftA1QQBoEdVNKHdtLwUCJK7Rqp09JM14bWqd1+G5bzUu/2zNPOYPMp6OLXgtaug8VIdxSJ0Jwl3dF2yvBi7Rg4PCVtNFbwn1FC4Z7GX6mU9Q6trbtNsMF0SpjoxUialRa/xc7p2wPo4gVpcyPpOqF2RHXBhNTo2rwi4PQVhM29+pmErl++WVwGC2oHZNemJ60=,iv:2pR2sYcE2J4X+dhoLdYFBd6e3Z927t91qIKCyzcsw5A=,tag:4CScPzmH1apjrEjh4k8i6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fs48f8rw9gj49ss5fapsy8euqln0dtrc5yg35fuq7c930jtkveps2swvt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cS9HM2lTUmJ3WDkyemcx
            dnZ3MTUxRkkxWjZoZnY1K0xlbzd5UEVscGdnClVuZFIwQzNoKzV0TFN2NkJvdk9Y
            eUxVazJ5aFBkOXFyYTBXTVlnMzREUXMKLS0tIHo5MzRkTGVyY295WmlGOUc0Rmh5
            R0hMZWYzVmcvTUwxTlFsaStyWFNLbGsKa8XXJmR0uAXZxwe4nZOua0zh3d8PFG1T
            Hbo2sTjALBPn2lgTNLFHho7IWmvsrrUnhl4siCT1GPXE1764YEw9gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-17T16:14:30Z"
    mac: ENC[AES256_GCM,data:ImjbwN0g8SmJ6EJ9+G9bSe6mVQAW38ZahIvCVCG8JkHtIMQi0o2OQt18MF30Vot+A34NlZdvDyyVyCHIHoDluZc5I/XH3R51X/D9a5rDCUj+vTx6pdDx4wyzk5gIdubtC0ClW9f+drwzNo/t4JDp9d3/r5lDw2SNSrGFq617wgE=,iv:W6ibTwXHbAQAE9AXSFCKPdJa1iFsbj4ueFdd9jIzVxw=,tag:C2HQt6c+LC94ThUl/lE1Jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
