# This transformation replaces all the dumb passwords and secrets
# with the actual ones
apiVersion: krmfnbuiltin.kaweezle.com/v1alpha1
kind: ReplacementTransformer
metadata:
  name: external-dns-ovh-secrets-replacements
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: krmfnbuiltin
source: ../../secrets
replacements:
  - source:
      name: autocloud-secrets
      fieldPath: data.ovh.application_secret
    targets:
      - select:
          kind: Secret
          name: external-dns
        fieldPaths:
          - stringData.OVH_APPLICATION_SECRET
  - source:
      name: autocloud-secrets
      fieldPath: data.ovh.consumer_key
    targets:
      - select:
          kind: Secret
          name: external-dns
        fieldPaths:
          - stringData.OVH_CONSUMER_KEY
