apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns-ovh
namespace: traefik
nameSuffix: -ovh
resources:
  - ../external-dns

patches:
  - path: external-dns-configmap.yaml
    target:
      kind: ConfigMap
      name: external-dns
  - path: external-dns-secret.yaml
    target:
      kind: Secret
      name: external-dns

transformers:
  - external-dns-ovh-secrets-replacements.yaml
