apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns-ovh
namespace: traefik
resources:
  - external-dns-configmap.yaml
  - external-dns-secret.yaml
  - external-dns.yaml

patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: external-dns-ovh
      annotations:
        internal.config.kubernetes.io/needsHashSuffix: enabled
  - |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: external-dns-ovh
      annotations:
        internal.config.kubernetes.io/needsHashSuffix: enabled

transformers:
  - external-dns-ovh-secrets-replacements.yaml
