apiVersion: v1
kind: Secret
metadata:
    labels:
        argocd.argoproj.io/secret-type: repo-creds
    name: github-private-repo-creds
    namespace: argocd
type: Opaque
stringData:
    type: ENC[AES256_GCM,data:xPmJ,iv:JyRiwYwNWnEZ9bM6Al9Pp0uiV6k7uM9vE0uRjwcJG+4=,tag:PGl6fjG+nEszih0xaLup3w==,type:str]
    url: ENC[AES256_GCM,data:fTCOXuxZB0WqYMP8fqX7ZKWavg==,iv:OFjvJvnWBPqFGmRoIvBi6r8EfNjrhXAsjy4DzFMBAII=,tag:xb9yNHizCDSQEeL0afLTJg==,type:str]
    username: ENC[AES256_GCM,data:DIL5av5tusE=,iv:TXMzFyrisIZ+vA7aFb2XfstA98/2CC+ydXeReFHlVT8=,tag:FYBV4VN7ithLMrDgEOxqhg==,type:str]
    password: ENC[AES256_GCM,data:neYsu+Q7ZAkZJxHe+P7VNIqiM1px4p1K+JBtKTmzoweol6TUL+vY+w==,iv:gRM2a6pnz6iZCUyJWIkooUHidlYyVKT10JGpWIkKk9M=,tag:RukpD9uQWb+oFmGtMuaNHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fs48f8rw9gj49ss5fapsy8euqln0dtrc5yg35fuq7c930jtkveps2swvt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUjJUMi9QMk83dFJBVito
            UHUxVkJXM0lFL2hOSFNmcHFKZnQydEtuemlRCnNWT3ZiZ1l0TTU4WWFCdStjY0da
            cGY5WFFvMktrYzdUNzcwZmgrSlNuR1kKLS0tIGttaDF3bHdlLzBLTC9oTzYzcGc0
            alFUVG1sVEQ4OXJyTHgzOXd1ZFJveTAKgNFMxc8nBk76qajdiKVPuLtjBFQ44Kub
            8UP1A2ybzB5a/oTUT5yqKOfxR9/mgx9A374rg9RIFwvQdsddai8D9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-16T15:41:27Z"
    mac: ENC[AES256_GCM,data:13vTP6KK+f/ytvu6i/higOVJUMwGCjqfpvqjzgk1jV6GNN8lu++F+qfGMth/vLs8CJhZ71/+Bf1hScKmywZYltffyNrn6CFV37QIhyTO3V2swHGfaAx9SQAo7Nvn+cUdIVc47bknMUkAWb04mcMlY7oU+fusa3hpTU6TbyeY8iw=,iv:gP52Ua2ZyXRG4RvXlBB1eqU8bDL7fbQNUH7b0Y1sZY4=,tag:hUqkt8y+bcnnZ+NfhqnnSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
