apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: external-dns-cloudflare-replacement-transformer
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: krmfnbuiltin
source: values.yaml
replacements:
  - source:
      name: autocloud-values
      fieldPath: data.cluster.id
    targets:
      - select:
          kind: ConfigMap
          name: external-dns-cloudflare
        fieldPaths:
          - data.EXTERNAL_DNS_ID
  - source:
      name: autocloud-values
      fieldPath: data.cloudflare.dnsZone
    targets:
      - select:
          kind: ConfigMap
          name: external-dns-cloudflare
        fieldPaths:
          - data.EXTERNAL_DNS_DOMAIN_FILTER
  - source:
      name: autocloud-values
      fieldPath: data.cloudflare.email
    targets:
      - select:
          kind: Secret
          name: external-dns-cloudflare
        fieldPaths:
          - stringData.CF_API_EMAIL
