apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns-cloudflare
namespace: traefik
resources:
  - ../external-dns-ovh
  - external-dns-secret.yaml
  - external-dns-configmap.yaml

patchesStrategicMerge:
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: external-dns
    spec:
      template:
        spec:
          containers:
            - name: external-dns
              envFrom:
                - secretRef:
                    name: external-dns-cloudflare
                - configMapRef:
                    name: external-dns-cloudflare
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: external-dns-ovh
    $patch: delete
  - |
    apiVersion: v1
    kind: Secret
    metadata:
      name: external-dns-ovh
    $patch: delete
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: external-dns-cloudflare
      annotations:
        internal.config.kubernetes.io/needsHashSuffix: enabled
  - |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: external-dns-cloudflare
      annotations:
        internal.config.kubernetes.io/needsHashSuffix: enabled

transformers:
  - external-dns-cloudflare-secrets-replacements.yaml
