apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns-cloudflare
namespace: traefik
resources:
  - ../external-dns-ovh
patches:
  - path: external-dns-secret.yaml
  - path: external-dns-configmap.yaml
# Import decoded platform secrets
generators:
  - ../../secrets
# Replace secrets in configuration
replacements:
  - source:
      name: autocloud-secrets
      fieldPath: data.cloudflare.apiKey
    targets:
      - select:
          kind: Secret
          name: external-dns
        fieldPaths:
          - stringData.CF_API_KEY
# Remove secrets
transformers:
  - ../../secrets/remove
