apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Note: setting the namespace makes the deployment fail as cert-manager creates
# Roles in kube-systm
# namespace: cert-manager

resources:
  - ./cert-manager.yaml
  - ./letsencrypt-issuer.yaml
  - ./testdns-certificate.yaml

images:
  - name: quay.io/jetstack/cert-manager-cainjector
    newName: ghcr.io/antoinemartin/cert-manager-cainjector-amd64
    newTag: dev
  - name: quay.io/jetstack/cert-manager-controller
    newName: ghcr.io/antoinemartin/cert-manager-controller-amd64
    newTag: dev
  - name: quay.io/jetstack/cert-manager-webhook
    newName: ghcr.io/antoinemartin/cert-manager-webhook-amd64
    newTag: dev

generators:
  - sops-generator.yaml

# TODO: Remove that once the images have been settled
patches:
  - patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/imagePullPolicy"
        value: Always
    target:
      kind: Deployment
