apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Note: setting the namespace makes the deployment fail as cert-manager creates
# Roles in kube-system
# namespace: cert-manager

resources:
  - ./cert-manager.yaml
  - ./letsencrypt-issuer.yaml
#  - ./testdns-certificate.yaml

# TODO: Remove that once the images have been settled
patches:
  - patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/imagePullPolicy"
        value: Always
    target:
      kind: Deployment

transformers:
  - cert-manager-secrets-replacements.yaml
