apiVersion: v1
kind: Secret
metadata:
  name: ovh-api-credentials
  namespace: cert-manager
type: Opaque
stringData:
  application_secret: Ug4yOimZdIbDnlYJFtsaNfpbrvNaJpwO
  consumer_key: 4vzeoro8p4ka02sr650mza9o3hlydmtp
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-apikey-secret
  namespace: cert-manager
type: Opaque
stringData:
  apiKey: fv71ywv1roof35lgobjdzafs63f2qum205mzr
---
# yaml-language-server: $schema=../../support/schemas/issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  acme:
    email: antoine@mrtn.fr
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
      - dns01:
          ovh:
            endpoint: ovh-eu
            applicationKey: 4KyIjUiRpDo4lpqY
            applicationSecretSecretRef:
              name: ovh-api-credentials
              key: application_secret
            consumerKeySecretRef:
              name: ovh-api-credentials
              key: consumer_key
        selector:
          dnsZones:
            - holepunch.in
      - dns01:
          cloudflare:
            email: antoine@openance.com
            apiKeySecretRef:
              name: cloudflare-apikey-secret
              key: apiKey
        selector:
          dnsZones:
            - autokube.net
