apiVersion: v1
kind: Secret
metadata:
    name: ovh-api-credentials
    namespace: cert-manager
type: Opaque
stringData:
    application_secret: ENC[AES256_GCM,data:ue7lKgGlDz1meZ4+gPsNCSPVWcytYPBLplrndO6mI6I=,iv:boZht+JMrR3P74YozcLCgilOhDIuTeoq4pNrfM1HhY8=,tag:cHHJoka1oqX062GbhmxSXA==,type:str]
    consumer_key: ENC[AES256_GCM,data:9D6E8OXj3beR4kzyevzKzVin8bAz0KOe+EMBUxiPCrQ=,iv:OjOvffBkFkOtPRwE1jILGa73G149XxXxAcourxOCkgI=,tag:y5Eau+LAey8YzyLECWylUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fs48f8rw9gj49ss5fapsy8euqln0dtrc5yg35fuq7c930jtkveps2swvt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUjBaZE5ybXV5aFdaclRZ
            Y05VY3NHYS9yNFNYZ0VvMDBibGRuK01CK3hzCmV0a0xxdnlHaXluU0JlenhIWkVm
            M2llL2h0UzdYeEJlU1F1ckV3UVFsRnMKLS0tIE04aGtHdlUwOGxPZVNIVnFlMzha
            TjNUTEZYRERFQWxKeG1MdHhReXZZWUUKOsGU1Hcu9w3FuYqi76s4pSTW5h+opfAL
            u+eZFK4GOlg7ZZ4H/4ELwW50gFf+lEtn8aj5GVshUHxvZNRZC3WggQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-26T23:26:29Z"
    mac: ENC[AES256_GCM,data:tgcM3dsSjPI//k36BPxhMQ9bZfTC8eNvHvmsAO4ELt8FeXu93+fkx047PcIKwJybI3ByV+rsetGjSczTZ1aaO5CoBynkFwd3QveZKTt2BBvzcJbcK81uQuFqVm42/IzMMvul8K7n2aT6CCUoCyAIxDbrWDsXeMAwVjerRJVsX6k=,iv:1D7g76gH1Ayku1AQHC1p2hNDOGYjOrnW219FvJsillM=,tag:g10Uq9DZk1vFLlYxlSNxdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*_keys?)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-apikey-secret
    namespace: cert-manager
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:OWFhAG0Nh3XP3RBnWMCGzk3k76BeyGaXYr8gvA33iUOXqVC14A==,iv:9zhUKaBHYvCTHRf9nKKTmykjlgYFgA1LIiyLEOTE1C4=,tag:CtMpFth1tbeqNq6PpMNjXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fs48f8rw9gj49ss5fapsy8euqln0dtrc5yg35fuq7c930jtkveps2swvt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUjBaZE5ybXV5aFdaclRZ
            Y05VY3NHYS9yNFNYZ0VvMDBibGRuK01CK3hzCmV0a0xxdnlHaXluU0JlenhIWkVm
            M2llL2h0UzdYeEJlU1F1ckV3UVFsRnMKLS0tIE04aGtHdlUwOGxPZVNIVnFlMzha
            TjNUTEZYRERFQWxKeG1MdHhReXZZWUUKOsGU1Hcu9w3FuYqi76s4pSTW5h+opfAL
            u+eZFK4GOlg7ZZ4H/4ELwW50gFf+lEtn8aj5GVshUHxvZNRZC3WggQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-26T23:26:29Z"
    mac: ENC[AES256_GCM,data:tgcM3dsSjPI//k36BPxhMQ9bZfTC8eNvHvmsAO4ELt8FeXu93+fkx047PcIKwJybI3ByV+rsetGjSczTZ1aaO5CoBynkFwd3QveZKTt2BBvzcJbcK81uQuFqVm42/IzMMvul8K7n2aT6CCUoCyAIxDbrWDsXeMAwVjerRJVsX6k=,iv:1D7g76gH1Ayku1AQHC1p2hNDOGYjOrnW219FvJsillM=,tag:g10Uq9DZk1vFLlYxlSNxdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*_keys?)$
    version: 3.7.3
