# yaml-language-server: $schema=./schemas/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: testdns
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  issuerRef:
    name: letsencrypt-issuer
  secretName: testdns-srv-cx-tls
  dnsNames:
    - "testdns.srv.cx"
