name: Publish docker image on docker hub
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Docker image tag
        required: true
        default: "2.3.3-0.144.0"

env:
  DOCKER_ORGANISATION: antoinemartin
  DOCKER_IMAGE_NAME: argocd-helmfile

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./repo-server
          push: true
          tags: "${{ env.DOCKER_ORGANISATION }}/${{ env.DOCKER_IMAGE_NAME }}:latest,${{ env.DOCKER_ORGANISATION }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.event.inputs.tag }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
