# Kustomization to add secrets to any kustomization.
# Include it with:
#
#    transformers:
#      - ../../secrets
#
# Then the secrets are available for replacement. For instance:
#     replacements:
#       - source:
#           name: autocloud-secrets
#           fieldPath: data.cloudflare.credentials\.json
#         targets:
#           - select:
#               kind: Secret
#               name: cloudflared
#             fieldPaths:
#               - stringData.credentials\.json

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./secrets.yaml
