apiVersion: autocloud.config.kaweezle.com/v1alpha1
kind: PlatformSecrets
metadata:
    name: autocloud-secrets
    annotations:
        config.kaweezle.com/local-config: "true"
        config.kubernetes.io/function: |
            exec:
              path: krmfnsops
data:
    cloudflare:
        credentials.json: ENC[AES256_GCM,data:mmma9HZuQACnxnEgo0tEb5XNqZWOfybxmHHFYEskIM0JHk3eBXJbRWf+237DTIHDxro+polhBDfe7Tnd/gHRR5iLnDyn4xO1m77v6IwJbeKvpyyT8epRe1Zm0h9uGCjrRlCSEkaSe3R9JE8jDOqv712Nj7FTNYONohNvYY1P1iQNj91FYiFTrrfWQkgAah7oWdNu5JK5NmYsdTpxNzdD2zmVxZJO3g==,iv:j1FF22mSKGG1vOBi1GAR0H+kxMo2/TNVdXYE0K8UGW8=,tag:4TrrQCc15kA2AdMHI7sGYw==,type:str]
        apiKey: ENC[AES256_GCM,data:keIQ2QXizqlR72ZWAlQHNvS5GxKr74/OzH9TRlm908PqDNYklKDO4Q==,iv:+cUSyXvNz+k7q8ETBXXYqqeScSQuYgyHSHyHqsjFrU4=,tag:FUmwG8vsbHdV6gVGRruXiw==,type:str]
    ovh:
        application_secret: ENC[AES256_GCM,data:txiQNTBIQjqYTjD38Vu88gf7YyE6PxWVK2V4ZhSlgUs=,iv:F9FvXP4Rac9DNEWsIea9X47Kc6r81lUFKodWYe/ESww=,tag:Ii+jVnTS2YWmb9tQPPHS9Q==,type:str]
        consumer_key: ENC[AES256_GCM,data:EmquuOxh/lxARo/Xf+CXBZh9V7OZ903aUHSNwYJxtfA=,iv:YFT+p41NyFkWqMTliWGzRlKUR0ZwH/PKV6nD0Tr3Vig=,tag:ipYN48a+K27SYXDhGgmdyg==,type:str]
    github:
        password: ENC[AES256_GCM,data:nIx/XvCGj7zypqvCkL+DD0MppE2CRCwy6UkflFPWZ/6Xxj4SDzd40w==,iv:zjuNlUtPgdzfSI2rTulc3l3ptwxxsyc3OSk0obcEEAU=,tag:08zVmYmlu4lUJEHmqs/BEA==,type:str]
        webhook_secret: ENC[AES256_GCM,data:iGPEqciboKGG6k1IRIr5Yn/kns9n7I+POJ3cuHelANU=,iv:YNjPHsIeFWMDVpoDRM8tCQvMN5csbCPZZNdbUN/6Hfo=,tag:zaxS2IlKNSNp5B6jXB/KLA==,type:str]
        oidc_client_secret: ENC[AES256_GCM,data:gz/Mc7qufMor4xyhiZ2eXxW9Fr25OJcAJtFm0dhY+amYJJxheVtMlA==,iv:hE9Nj9nrFyrks/gjorh71PcCMMg1qM7/k06gVVcVWs4=,tag:SAcb7uKW4iC0X80UYsjICA==,type:str]
        ssh_key: ENC[AES256_GCM,data:AFAs77TVYXgScWepyHNS5DsMrFutGBKvD4eHjBO7BJ3zB1B06n97Cu1Ebd6V9wTGNMKbBILFg6+M3a/wyILbBsN2P8xCjY1qN5cx1tXBkU9lHaIVE368cW7Kj2lEcq+2h9Nwq3YvKelEJDCOuhI/9La0/8PO52m0uouFiT93hMlQXIYXDBCJ7h3HqHz3hCTq+YxM3cvG0hUSM2PlreJqHwv4PjmQK1l0aNVuuWZST6mlkElg5msAcdf+2bFUZPjbvLsDuxcT03weT5cfJdlcwgkEeboCegd5ExM5TkrTGww+W6PHigHXUoAme5XKbFaIAB6X16my7n1LREG4v8eMVOelsqBTSlDjE2wqeX/ezPQnbRDZ34vXmk+dClhVDnlyX1aq7DuVJ55Tq4L23zHmvKF8tcshUdnrxlXfKY0UI+XXSN1Fmgxuh3YxAeKFP5+LUjb6UB9VwxqZbxRaez5T2zoxDeLH5OmkezhfT3VaCrj0sq9HGGTQjYznFoF/4MrxBVS32DvBh5kd3an1ARRwMXUTa98ewdP8xs5K,iv:0EsJC6WcNYTJQWn+1f61i+1gw7/O6HArYwCRlOz5Tp8=,tag:9Tlt60F8i+k2wOWm63s0rw==,type:str]
    sops:
        age_key.txt: ENC[AES256_GCM,data:XXyvrpKJS5jAzcYyWFF2YqkO9dIGzehhDpAs0KUbHoEPqQpsrtJGcnqgE09V/5wnqqUhcl80fK9DLbYJhUOAaKtd26ZPubdWbEPoEnp79kEmNoL5RFPLjAXTMkBNlnE4WtRIk5Z+4Tqoelz/xibKNrmjcRitSHwqQKb6E3olcZXn0j5gYp+BFvkc8VPxcGfuJ9AR7Czx5oNNY88f4Y4/s1WdgHsElEG/E313zf1WuTrvMi/dLOC88F29bSwSBEEx3M1ckiWmrvyj50YlyG3jAhQhpQ+f1pvBJEhKL4ZXFk5wa4oeRmYOcyHW+AvTUEuB9znRxbGv58c=,iv:nuyLQtgkr6d3qdebNPy5812oPx/DBzo+O2V7bYO/10M=,tag:LpbJ1jBJPK+/IsAuXwYtGA==,type:str]
    argocd:
        admin_password: ENC[AES256_GCM,data:MwEr8JYssNXcUZK8gcTJCb+DkYpITtYMeRxsqPA7GQt9ZaE4CcpaoG+o7E/9xiFmoG5+SgTWGp5LBpxJ,iv:2uXxuIZM8M+U92loTfx4MHIXtvVMSBMPwlagvRkoF8k=,tag:KiFe+tnoupjo54q27wfGXA==,type:str]
    chisel:
        AUTH: ENC[AES256_GCM,data:ryHNhytZ9hB8T3c98g==,iv:Q2VSN5Amuw3e48YzsQH8aTAI5mxcCToWfhJ5mkJ1sog=,tag:THIFAGQ5NqOpIIA53ar53Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age166k86d56ejs2ydvaxv2x3vl3wajny6l52dlkncf2k58vztnlecjs0g5jqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QzZ0bkxrUjNZZSs2SmJx
            dnFheFNyUGRDRjR2bFpjc1Z5QUN3ZHpwYlhRCk5KZ3B5bXhmR29IWHhLaWRNZXdv
            Q2pRekxoZk81OFdFbk01QktERWtvcTgKLS0tIDc3VTFZMm8rRFVRUm9Lb0I5dEl4
            aWpRQVE0VnArWmhKK2l5eTNSSkRRL1UKewZKQU3E+TEkZY4qPteB1bDRe1/pvIXb
            iMjs4GS2nis7bHlWOYZGjNyv+UAMg/hAIX4t7chWydotIjWuDh4NPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-01T14:46:37Z"
    mac: ENC[AES256_GCM,data:Rqddn/GIZ8LsVzcsHkFBjgznTUl/qNxNy6aZ2Toapk+jecgSEV+C26H9SqQ0kzlQAX3cXrbJTVhkwmqhjUHNfjliXmzphCPvGBTQrFIL8k5B0Bp4xuaE7PITXyuclj+RVOQTjMH7Nn8R/ZpZD46v5oRSfllBHAMtlvnzijIHeQY=,iv:BT81LAOIsJYZPYTW9nG73sQJuulWo+z5FKeqAiVR8hg=,tag:72mnpREXlKJA6AyFN4hpmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*_keys?|admin|adminKey|password)$
    version: 3.7.3
