apiVersion: karmafun
kind: SopsGenerator
metadata:
    name: autocloud-secrets
    annotations:
        config.kaweezle.com/local-config: "true"
        config.kubernetes.io/function: |
            exec:
              path: krmfnbuiltin
data:
    cloudflare:
        credentials.json: ENC[AES256_GCM,data:NJRg9Z3nmS1PWXaYuVC0NlENBIY96EWBY6+AzYKFnkTUsmWSFpUGAM9mFBHyJGXYGn9y30moflj0ZvASLvwZZplT+fsoSnuPaSu+riDkjmtiTHmYD+zJ+5FLQulXhIegID2Nj/mLhnoLxK7l+XBOI1CSC/Ri9hSQw4FQeC8Sq2kXv0O2WyNOI24O98zEifRIzQDw/zNIxpGpMOEzKy2G7FS3oRPIdw==,iv:j7RCa6LUSAwZJSLp64kqANVNSSSdEbuO+njUwPGvp5w=,tag:rF2gMqM1CB9lxLcdobV8Ag==,type:str]
        apiKey: ENC[AES256_GCM,data:U3846MznZtqqCnlcJKUbT1zidj+JhPbm9L0YsVkzF1vNuw9dtEJqIQ==,iv:2JG0w3t88/m43qyAUuf0C2CWQc0vOkRepTfPGYUCukg=,tag:/ffldEMkkwI3zGXsKoiTkA==,type:str]
    ovh:
        application_secret: ENC[AES256_GCM,data:KhLRnSR2xU/O0542dL8uxaCSLJTmd30+/7OkbJSIks0=,iv:qsKAcEtjH+07CF5Hzj7fjTVt4HVMcrIIBxuWl0GdZVc=,tag:O4Eugza1DNwR8MkWd6Y+mQ==,type:str]
        consumer_key: ENC[AES256_GCM,data:w+qZg/g92oyMewNgDsOJ41Jc3CNoO3Bj3HSPcCQMIRI=,iv:qKrQhkphKLMoqoPHgskyKAUgryVD5np9nrR0EotVwrQ=,tag:ywxLNwXEHxZKQ62+P6fAtQ==,type:str]
    github:
        password: ENC[AES256_GCM,data:1GpsO/M3CaCgXjRGTtqjrQWb9UeymLIt93gB5D1PnyLoQwExYncoZg==,iv:q+L8fsfPqBkNVPPgMEIErdpyRoS65UdGmH7zp3goRYo=,tag:s6Gt7/AiGlUCFM/j9jADmw==,type:str]
        webhook_secret: ENC[AES256_GCM,data:PXqRGH0sDPMDmBKfGhPiJl4Wtotyi0Brs0HKu+hzS3U=,iv:iJBx8KUyVc+HP+McKEc5z8VN2giseAPM7f086bsp6k0=,tag:2QAppmkMLTOyWRJdEAprOQ==,type:str]
        oidc_client_secret: ENC[AES256_GCM,data:weKaRzi/pTowsub7UmeWtrM/vBeyVTy4mOiB+0+QsI+IpN3acOuwcQ==,iv:czXoDWEVIEC3rYS5oYVMOl/lY5O103U1qVPyO/t3kYQ=,tag:41BNU8tO3esrgP+1Oe8GWg==,type:str]
        ssh_key: ENC[AES256_GCM,data:6quQbHcTp+AB9Xh/mg7EEN5WbuKst5Nv+qb71MS0cm8o6UgozE8w5jdy+TCTIztbRjoyCNUTh0BoBExYJxDnd6XwIf9JD5vRxd1aofJtHAYQKkKZqeO6nDIAaIqc+GA7nDfoOzTLCMKjAC59bw+LA+yhvLbqMYH3PsV42WyVOBkVP4eungTcPJXJsR0ewmGnqTTFYwOwCskg2x0NF49wOAO7qgrvsf7QYPf1Vcv2BHeV1wiPDpokCQ0eGxd7EHDwo+8fzsjv+leywBJicYEqRGsrhjZQBmi3r8BtpK4+YQooEO0u2O7JUehSF7XyfsVX+bFBqParTiVL18DyfrPDh2giBiYIMeMuaVqUcCo68IG/IzeVJ0wqHmrG4Qxfv9SvHqMqlCdBQ8AhbKxxjw1dxAH7Y+adVSOJDWpyZs5mH3a1X8LZ23y0PxkyKqbAHSlPsBMU96XYODmg54H9RKFkqz3Ff5GjwlHuk/2OimgstMGnDpJ96DTAVom8q7glUSer6WLr6dYkfK8Gb6fPv+hOMOn0Y+fb8iHM7Aar,iv:28oBY5Ll7lILhBVItz7zLO1HzRijDbvcBCatesx77R0=,tag:uD4hKwC5IcH8kSgbVFlJ4g==,type:str]
    sops:
        age_key.txt: ENC[AES256_GCM,data:ymy/mALf3BUYOJngSb2UK60cAdt3tIjX1sYEGlYFw9r6bMx8qAoFDIo0u/1T5+RPTETQyl0Ahcfo/cy0Ox+gVnsCIoVPDwaJumz5w3DP8rEwF/bCcloMy00dQBe+6FDxz7ncLeD4QWMekheT7eoMkN5U0Dw98AluOUimvboSBz/g8Abmp6bxVXP11j3hWH5cijx0MO97XeaR2u+ZC+pGWcsMJs5i4EurLmo+55PEWErM1OYMz8C4DJL0k7vL//mw0EvYoKgCIcJumnUB+PSKjWMFLEoOafRQa+Z3Cj5+AWPFo8qeEZ0CxEnnpkObtWEy7BPI+175y/c=,iv:Qu0G9sN/uQHlQBDCSHtODGp4FzVjmVV2HEa4unPC//I=,tag:Km3r1fI1N4WcILa6saQIJA==,type:str]
    argocd:
        admin_password: ENC[AES256_GCM,data:mN0zZL0KgPSXKjtrEaNg6c6s+cr4CJiKLeweap45aO6rTNY4fyYmkg+lhEK2SUXU781waINC8YSyhtWG,iv:9nRLc98Atf/3nzNMQro+Uh6DiFN6OZfl4VtuLoEEUbE=,tag:OyC0ubyrinYM+pLaYxNOYw==,type:str]
    chisel:
        AUTH: ENC[AES256_GCM,data:GlfDzpva4j6xdQQTrQ==,iv:tyMpxoPSrTCBoUZ9D3UfSMNI1bc+B2u/jiavAVpAcTw=,tag:DBx5CrNUW2LvsaPPsPRrgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age166k86d56ejs2ydvaxv2x3vl3wajny6l52dlkncf2k58vztnlecjs0g5jqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUnFYaElDQWhjaFJkNDM2
            R0FWZGdHY24xdjlNMENPeTF5K0hRVWZoVEZjClcwdXZrRUFudXNoNEVUU3QxSnBG
            azhUNU1hazZLanJoajNmSTBGejIvL2sKLS0tIHk0T1Z4TW05dkw5Lzk2NVViZDZG
            bkNGUTVGQUxpejl3RnV3NzJPbURRNGMKLFMjqMnBvXwdibABHCwjeAKP7ty71xHg
            JaEz/i6BuqImQEaH0J3oqBJYks6E9A/oATadHxxDDrOec8Q5F97HKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-04T11:38:24Z"
    mac: ENC[AES256_GCM,data:+9roRXrJ8S+obl1dsU+ArN0kmTAQS/Oer/9ZqrwxKOckXENQ020KSNvr6kllkIZDTI4VDfsWcyOkGpOeRicPfabBdOUR5Ig7+SQyWw3ag3i4P18glfVyo2SBSUZEH5UWzPkF92Aip0Hu0Fcqy0RTdeCmtcunVFHRTg/RO0NqJxU=,iv:4OFYRkCxDVuJSoum8aw/uP1lFhrurU2WM+mLVSVmDAc=,tag:gSsCJgHnYZcyevnn3nyi8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*_keys?|admin|adminKey|password)$
    version: 3.7.3
