apiVersion: autocloud.config.kaweezle.com/v1alpha1
kind: PlatformSecrets
metadata:
    name: autocloud-secrets
    annotations:
        config.kaweezle.com/local-config: "true"
        config.kubernetes.io/function: |
            exec:
              path: krmfnsops
data:
    cloudflare:
        credentials.json: ENC[AES256_GCM,data:lEUV8/2l0qJe2k518xq85BbRjmx1WnsA2Nh/17dGi4DZRbt5vtSfHGwlv8ehAf63VuxxFo2e6pEfaeHMhLuKgg3gFXIV2yyB/y0pTAMcDXVhLzeYerQYTYAZaFotwUc3N85m0mQa+LVl5Pi5vMnOEUvQrPwdvzp0wC8Q2tLxnG0JgV1oa3r1xg7IyHI0XW5yJTLx5lVUACECAUM37nIOeLcAxNE5xQ==,iv:ngLeY32/TOw/YIFJiB0bo+18F3tWjtI+eRCfzECONfA=,tag:WjcfMbabHbsH4fvGaZx1Tw==,type:str]
        apiKey: ENC[AES256_GCM,data:VSTtgWHOTeKmOr6NoN8k04JHNa1ot8tS+PbohOVWfQqATAcemg==,iv:81BYQYVzG8Fq5ZHHU/8a03mXwvPPxQF7BDGSwL2mkz4=,tag:vFdrLt0a/81cqgie50+qXA==,type:str]
    ovh:
        application_secret: ENC[AES256_GCM,data:Qbln1Kud/7vSCp0E9Ur7lAxFu4QUChrtHoZnRVqRxjw=,iv:xc2e5RXPcy9rHngba3mw+cpWYbCEGItu6eLI5KYXOYk=,tag:c9XA0QDpO0Mv8m+Hh4zWVw==,type:str]
        consumer_key: ENC[AES256_GCM,data:OE8UAUDgAn3IZR0Tn8EphqYAdkJXqjlkMNSoZONW7JA=,iv:/+gEZTSnQXONmbY/TZKWTPqETk1EAokE5e32j0oozXQ=,tag:4ENDo/UojU40nRxVWXLtIA==,type:str]
    github:
        password: ENC[AES256_GCM,data:0bIHouhTMXdyMvDcsUkcOTD5wKqdfLbgMHQNjEH6NmoGdz0wECiOKw==,iv:m7+wrp0RURsqS36PlovCJ76p2VWhuSNzPH3oty1mPKA=,tag:djFn8U4OSQs63D59yh+/RA==,type:str]
        webhook_secret: ENC[AES256_GCM,data:vAMDHhMbzLiKkEW4Wt7A/y6L6xvr6Wz7,iv:FbyvxURbO6Nxx51be2bEmjjx/Dlpqss0yLmahjANdy0=,tag:X1ExpeybHwTCSsc1l6hxmw==,type:str]
        oidc_client_secret: ENC[AES256_GCM,data:e7hw6T9z479SyncxU2X5htwAKxH6tWiYvvrLolkPapTaEUO0JEueUg==,iv:ruoT6HkpCKbZqWtBA/YaDUteaQ3Ope8wAIDws9KHHis=,tag:m3JWNGGMBDAkHS0bkp+Plg==,type:str]
        ssh_key: ENC[AES256_GCM,data:teNuelnHksxkOF95AM8b2t2u9A0bq972zqvjrkMWKH0wamA1vlbha7seAU0VmgnWJdCvpNb/zdrjH4WeJRRuElsVX97HQODcQJ6u3fkzX5cywMRfyU5oKud/NMeknHRuJbC8n6T2fNvfzBvm8gdScAEN9dn44J4qx0rFWXfypqGbTedPJvt5B1vMMa0o2S72H0jjXykuzos39b7uV0AfvgO4w5dH3o7mitxX3Gmb0s1r07sPCK+5Nl4Zm4G1Q+D6TxGkIMGwcBqSzleo0u3MXBDjNGVGEAXBOFTY/kJdQS0J1MefchBUXNs2XXCP/ImqoYo3jUitRcj6LRXwQSi56W4wVdWXX5N8nRg3Msai+CGLlANMuNV8UWI/5yRZRcvAAVRwdQzUb+0R5aO8kuV9HcN8TwYwbACjkVOywwTyfCUSu8av1IKNFnfxehrsT37YwZaQ7jd0ajPDr2dclMGLRWnna0/ePMvu4dLQcS9lgTxIFviMqsGxxXCQXvI1vuwk/IIhBgQR42GrDXx1GpvuXvmQK8ExEa7uJec3,iv:+Keps22SIjpz67e3tx8jSu/N/8MDqukYW3RtaOiSR4Q=,tag:5a3yCoBFuHUXwMd+vnMoDQ==,type:str]
    sops:
        age_key.txt: ENC[AES256_GCM,data:zmCDm6yPNYNQ7d40/iYdU/rfnZgKW4hF20Mksk9xCKV2LmrHGgMmyvDBKwgZk9Z27neb0i+zB+/j9fAIo64sC7zJGptNux3Fg5mGkiBevkMmhs+ziGA68Y35G5yvtZP6CceuQrdJGSgDqQC+UilrB8W2ly3flNQcY1CELSU3IgfteHmmulqFNZEwxCFJGrO6yAqHmfeQ9WNf76tgC8HfLm/5yLZwOq1yWbxI1vWu0jCAs7FtuS0u0QnJlJ/cxDfBvPKltS7t428k1Uj2hqTF5hgSd80VMUNo3AajYyCCKWtbIHBVeOGB/iRcNfEK3vBqYJuZ/x8novQ=,iv:giiIaFJjcsoYatUxL99faRQql97AFB8G7l1lUZ3js14=,tag:11yCm7rwYh+AXgNiMC4LUA==,type:str]
    argocd:
        admin_password: ENC[AES256_GCM,data:frUNkXZsv27dm9Sx3/qFgy+GpMk6ybd+asyOhodEk35cE1AF/p40yFjJ+6Jh0qq4ed1jLmGSy6eDZBnC,iv:oD61EHi9Z+hrLbnRhKHmPSmZVBEeC2skUT56UgGU3Ew=,tag:bzX17BlnEyhHi6H/3bjGKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fs48f8rw9gj49ss5fapsy8euqln0dtrc5yg35fuq7c930jtkveps2swvt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNHQ0UWdwNWxtdVBucVJu
            eGQweXYrM05oYkVBajRFZE15ZG5GSUd2NlFvCkYyMlhZaW40TVI3bjlzV3Ivc01C
            RDl4eE52MXhvdGlZNkc2V0RMWGo4VFkKLS0tIDd4WFloUWxiR1NJVTgyUm0xMCsz
            bkd1a0k0b090aFYrdUJweTBDQmF1LzgKBSVkTT0NWKyCfk8DIDtiwYnDPyG6yPte
            BT4pH81S739WZ4b8/yYM+pbFi8Ngwcd0gouhQaU1nbf6vzDZrIWA4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T08:29:31Z"
    mac: ENC[AES256_GCM,data:1682wIeygPV/n8VcQlCWgmITelRSwe4OwMKpugFV2K/WSiDD7Hvn5KEnUIDTMw9KBbacOJD9tbpczULsbPCrBPXOnJSwPGyb/PMaq12UPxIVRgQVANLvh9HxY+NeOY2UHJMEN1AZ4/g5LrO0IBEzmHbolaxcDfbCBbM9jKzr76k=,iv:TCEux08wdzh/uteFAi2sAaFFZC1ee596Z+O4fgpFlgk=,tag:Pkz4iOlz1AslAarWSycgQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|.*_keys?)$
    version: 3.7.3
